### ISSUE TITLE
Options window is not displayed properly

### ISSUE THREAD

**Issue by atsiakas** [isshiki/ReFwdFormatter#1]
Hi, 

When trying to access the options window for the add-on (Tools -> Add-on Options -> ReFwdFormatter) the window is not displayed properly. I have uploaded the relevant screenshot. In order to close the options window I have to press Alt + F4.

Thunderbird version: 60.0
ReFwdFormatter version: 1.58.0
OS: Windows 7

**Comment by atsiakas** [comment]
I can't upload the screenshot at the moment. Maybe is a proxy issue. I will try later from a different network.

**Comment by isshiki** [comment]
Thank you for your issue report.
I'm trying to fix this issue and uploading to addons.thunderbird.net.
Usually it takes about a week to review, so please wait a little more until it is published.

**Comment by isshiki** [comment]
This add-on is updated to version 1.65.0  in addons.thunderbird.net. Please try this.
https://addons.thunderbird.net/ja/thunderbird/addon/refwdformatter/

I'm closing this issue. Please contact me if anything happens.

**Comment by atsiakas** [comment]
T H A N K   Y O U !

it works fine now.
