### ISSUE TITLE
Text moved to the bottom of the communication

### ISSUE THREAD

**Issue by atsiakas** [isshiki/ReFwdFormatter#2]
When replying to an email, the text below my reply is moved to the bottom of the email. That is, the email I am replying to (most recent email) is moved to the bottom of the communication like it was part of the first email sent.

To work around this issue, I have to select all the text of the email before pressing on the reply button.

The issue is not happening for all the emails but quite often. Let me know if additional information is needed.

The table attached demonstrates the email communication before and after I press on the reply button. 

[Text moved to the bottom of the communication.docx](https://github.com/isshiki/ReFwdFormatter/files/2387906/Text.moved.to.the.bottom.of.the.communication.docx)

**Comment by andyross** [comment]
I'm seeing this too.  It's caused me to disable the add-on, as it's make a complete mess of the history.

**Comment by SemarangIbis** [comment]
I'm also having this issue. Also quite likely to disable the add-on because of it.

**Comment by cqfast** [comment]
I first noticed this ordering issue when I attempted to reply to an HTML email thread from my Thunderbird Sent box -- replying to a reply that I had already written.  I've also been experimenting with SmartTemplate4 reply templates, so perhaps ReFwdFormatter got confused by my reply template?  When I disabled ReFwdFormatter, then my resulting reply had the messages ordered correctly (unfortunately still with the undesired quote bars).

**Comment by gazzari99** [comment]
I had this very issue the last few weeks. After deactivating this plugin, all was good again.
Bud I did notice something that may be of help.

If I reply to an email some of the original email was reordered. If I forwarded from the exact same email, everything stayed as it should. So it appears to work OK with Forwards, but not Replies.

**Comment by isshiki** [comment]
I'm sorry for this issue and your inconvenience.
I rewrote the logic for html mail reply.
I sent the fix version 'v 1.65.1' to AMO (addon.mozilla.org) about  a week ago and I'm wating for approval.
So please wait for some days. Thank you.

**Comment by isshiki** [comment]
This add-on has been updated to version 1.65.1 in addons.thunderbird.net. Please try this.
https://addons.thunderbird.net/thunderbird/addon/refwdformatter/

I'm closing this issue. Please contact me if anything happens.
