### ISSUE TITLE
Support for 68.x

### ISSUE THREAD

**Issue by figue** [isshiki/ReFwdFormatter#3]
Hello, will this addon support 68.x? It was very useful for me at work. Thank you!

**Comment by rex-dtx** [comment]
I fixed it and created the pull request to this extension :P

**Comment by rex-dtx** [comment]
> Hello, will this addon support 68.x? It was very useful for me at work. Thank you!

Please wait Mr Isshiki merge that :D
https://github.com/isshiki/ReFwdFormatter/pull/4

**Comment by figue** [comment]
Thanks!

**Comment by isshiki** [comment]
I submitted the fixed add-on to addons.thunderbird.net.
I think it will take about a week to review.

**Comment by rex-dtx** [comment]
Thanks Isshiki! ^_^

**Comment by isshiki** [comment]
This add-on has been updated to version 2.68.0 in addons.thunderbird.net. Please try this.
https://addons.thunderbird.net/thunderbird/addon/refwdformatter/

I'm closing this issue. Please contact me if anything happens.
