### ISSUE TITLE
ReFwdFormatter does not work when SmartTemplates is also installed

### ISSUE THREAD

**Issue by atsiakas** [isshiki/ReFwdFormatter#5]
I am a long time user of this great addon. Thank you very much for creating it.
I have been using this addon along with SmartTemplates in order to have outlook styled replies. 

After upgrading Thunderbird to version 78.4, ReFwdFormatter to version 2.78.0 and SmartTemplates to version 3.0, the addon has stopped working. When replying to an email, the blue vertical bar on the left of the email is not getting cleaned and the blockquote tags are not converted to div.

If I disable or uninstall SmartTemplates, then ReFwdFormatter works fine. The OS I am using is windows 7.

**Comment by klaus1313** [comment]
I confirm the same problem on Win 10.

**Comment by RealRaven2000** [comment]
I might have a patch for you but I have no idea how to create a PR on your repository.
[refwdformatter-2.78.1pre7.zip](https://github.com/isshiki/ReFwdFormatter/files/5772049/refwdformatter-2.78.1pre7.zip)
github is so complicated.

**Comment by atsiakas** [comment]
> I might have a patch for you but I have no idea how to create a PR on your repository.
> [refwdformatter-2.78.1pre7.zip](https://github.com/isshiki/ReFwdFormatter/files/5772049/refwdformatter-2.78.1pre7.zip)
> github is so complicated.

Thank you RealRaven2000. I have tried your patch and I can confirm that it works as expected for me. Thank you so much!

**Comment by jkavery** [comment]
I had the same problem with Thunderbird 78.6.1 in Ubuntu 20.10. Thank you @RealRaven2000 for your patch:

> I might have a patch for you but I have no idea how to create a PR on your repository.
> [refwdformatter-2.78.1pre7.zip](https://github.com/isshiki/ReFwdFormatter/files/5772049/refwdformatter-2.78.1pre7.zip)
> github is so complicated.

I took the gist of the patch:
>      let indexCite = details.body.indexOf("class=\"moz-cite-prefix\"");
> \+    if (indexCite === -1) { // fallback in case SmartTemplates is used:
> \+      indexCite = details.body.indexOf("id=\"smartTemplate4-quoteHeader\"");
> \+    }

and applied it to my Thunderbird's extensions/refwdformatter@masahiko.info.xpi:background-script.js

It worked fine.

**Comment by kbauer** [comment]
Hello!

A similar issue exists with "EnhancedReplyHeader" (https://github.com/docgunthrop/Enhanced-Reply-Headers). 

    <hr ...>
    <table class="ehr-email-headers-table" ...>
     ....
    </table>
    <blockquote type="cite"
      cite="mid:ffffffff-ffff-ffff-ffff-fffffffffffb@server.com">
      ...
      
I run into two issues when trying to debug it:

**1.** The line 
 
    try { details = await browser.compose.getComposeDetails(tab.id);} catch(error) { notCompose = true; }

sets `notCompose = true` frequently.

**2.** The addon seems to do its work, but the body text is not affected. I suspect there is a race-condition with other addons, that modify the message body, where the other addon overrides the changes of ReFwdFormatter.

**Comment by isshiki** [comment]
Dear all,

Thank you for your patience and for bringing this issue to my attention.

In the latest version 2.128.0, I have fixed compatibility issues when ReFwdFormatter is installed with SmartTemplate4 or EnhancedReplyHeaders. Please update to the latest version.

Please note that due to the way this add-on is implemented, based on fragile HTML ids and class names, it may not support all combinations with other add-ons or additional features. Your understanding is appreciated.

Thank you for your continued support.
