### ISSUE TITLE
Filed upstream issue

### ISSUE THREAD

**Issue by alkisg** [isshiki/ReFwdFormatter#6]
This extension is great, but it works after thunderbird has already quoted the body, and post-removing the quotes is causing various issues. (I wonder if it would be better to start from the "Forward inline" state first, which includes the initial body in an unquoted form).

I just filed an issue in thunderbird, requesting that this functionality is implemented upstream:
https://bugzilla.mozilla.org/show_bug.cgi?id=1815098

Anyone that wants could chime-in, it would be great to have even a hidden about:config option for this function!

In the meantime, thank you for the extension!

**Comment by isshiki** [comment]
Thank you for your feedback and support.

I noticed that the request for this functionality has been rejected upstream in Thunderbird. Given this decision, I will be closing this thread.

I appreciate your understanding and continued support.
